### ISSUE TITLE
Central CLI dispatcher handles communications between components

### ISSUE THREAD

**Issue by juniorbird** [team-jwt/pleated-slacks#19]
There needs to be a central dispatcher
- Find the cwd
- Find the package.json
- Kick off analysis
- Receive results, kick of Docker Compose file build
- Receive results, prompt user for next action

**Comment by tbywong** [comment]
- be able to confirm the services we've found before creating files (parse before building)

**Comment by juniorbird** [comment]
Workflow:
1. Parse package.json but don't build
2. Present to user what we think you have, let you edit
3. For everything you have, assign a port
4. Save dockerfiles, compose; create shell script

**Comment by juniorbird** [comment]
Output format:
- .txt file
- Each line is a path to a Dockerfile

Shell script can read and execute that
